image: Ubuntu  # образ для сборки

stack: jdk 11  # версия JDK

branches:
  only:
    - master  # ветка git

build: off  # будем использовать свой скрипт сборки

install:
  # запускаем SUT (& означает, что в фоновом режиме - не блокируем терминал для запуска тестов)
  -sleep 30
  - docker-compose up -d --build
  - java -jar ./artifacts/aqa-shop.jar &
  build_script:
  - chmod +x gradlew
  - ./gradlew clean test allureServe -Dselenide.headless=true --info  # запускаем тест, флаг --info позволяет выводить больше информации
