image: Ubuntu  # образ для сборки

stack: jdk 11  # версия JDK

branches:
  only:
    - master  # ветка git

build: off  # будем использовать свой скрипт сборки

install:
  # запускаем SUT (& означает, что в фоновом режиме - не блокируем терминал для запуска тестов)
  - docker-compose up -d
  - sleep 10
  - java -jar ./artifacts/aqa-shop.jar


build_script:
  - sleep 15
  - chmod +x gradlew
  - ./gradlew clean test allureServe -Dselenide.headless=true --info  # запускаем тест, флаг --info позволяет выводить больше информации