image: Ubuntu  # образ для сборки

stack: jdk 11  # версия JDK

branches:
  only:
    - master  # ветка git

build: off  # будем использовать свой скрипт сборки


build_script:
  - chmod +x gradlew
  - docker-compose up -d --build
  - sleep 10
  - java -jar ./artifacts/aqa-shop.jar &
  - sleep 10
  - ./gradlew clean test allureServe -Dselenide.headless=true --info  # запускаем тест, флаг --info позволяет выводить больше информации
